name: automation_regression

on:
  workflow_dispatch:
    inputs:
      testExecKey:
        description: 'Test Exec ID from Xray'
        default: ''
        required: true
        type: string
      projectKey:
        description: 'Project ID from Xray'
        default: ''
        required: true
        type: string

env:
  ROUTE: src/test/java/suites
  NAME_SPACE: "_"
  
jobs:
  job1:
    name: Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  job2:
    needs: job1
    name: Matrix1
    runs-on: ubuntu-latest
    container:
      image: mavster/ubuntu:20.04-ff51-mvn
      options: --user 0

    strategy:
      matrix:
        Plan: [login, details, pnl]

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v3    
          
      - name: Compile and package our project
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x16 -ac &
          export DISPLAY=:99
          export NSS_USE_SHARED_DB=ENABLED
          export $(dbus-launch)
          export NSS_USE_SHARED_DB=ENABLED
          mvn -Dmaven.test.failure.ignore=true test -Dsurefire.suiteXmlFiles=$ROUTE/${{ matrix.Plan }}.xml | tee test_results.txt

      - name: Listar archivos en el directorio 'aws/'
        run: ls -la xray/
        
      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl jq
      
      - name: Create test execution JSON
        run: |
          echo '{
            "fields": {
              "summary": "${{ github.event.inputs.testExecName }}",
              "issuetype": { "id": "10007" },
              "components": [
                { "name": {{ matrix.Plan }} },
                { "name": {{ matrix.Plan }} }
              ]
            }
          }' > test_execution.json
           
      - name: "Import results to Xray"
        id: import-to-xray
        uses: mikepenz/xray-action@v3.0.4
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "**/target/surefire-reports/*.xml"          
          projectKey: ${{ github.event.inputs.projectKey }}
          testExecutionJson: "./test_execution.json"
          
      - name: "Use testExecKey"
        run: echo "The testExecKey is ${{ steps.import-to-xray.outputs.testExecKey }}"
 