name: automation_regression

on:
  workflow_dispatch:
    inputs:
      testExecKey:
        description: 'Test Exec ID from Xray'
        default: ''
        required: true
        type: string
      projectKey:
        description: 'Project ID from Xray'
        default: ''
        required: true
        type: string

env:
  ROUTE: src/test/java/suites
  NAME_SPACE: "_"
  
jobs:
  job1:
    name: Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  job2:
    needs: job1
    name: Matrix1
    runs-on: ubuntu-latest
    container:
      image: mavster/ubuntu:20.04-ff51-mvn
      options: --user 0

    strategy:
      matrix:
        Plan: [login, details, pnl]

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v3    
          
      - name: Compile and package our project
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x16 -ac &
          export DISPLAY=:99
          export NSS_USE_SHARED_DB=ENABLED
          export $(dbus-launch)
          export NSS_USE_SHARED_DB=ENABLED
          mvn -Dmaven.test.failure.ignore=true test -Dsurefire.suiteXmlFiles=$ROUTE/${{ matrix.Plan }}.xml | tee test_results.txt

      - name: Listar archivos en el directorio 'aws/'
        run: ls -la xray/
        
      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl jq   
           
      - name: "Import results to Xray"
        id: import-to-xray
        uses: mikepenz/xray-action@v3.0.4
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "**/target/surefire-reports/*.xml"          
          projectKey: ${{ github.event.inputs.projectKey }}
          
      - name: "Use testExecKey"
        run: echo "The testExecKey is ${{ steps.import-to-xray.outputs.testExecKey }}"
    
#      - name: Authenticate to Xray
#        id: authenticate_xray
#        run: |
#            response=$(curl -X POST \
#              https://xray.cloud.getxray.app/api/v2/authenticate \
#              -H "Content-Type: application/json" \
#              -d "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}" \
#            )
#            echo "token=$response" >> $GITHUB_ENV  
        

      - name: Update Jira Issue
        run: |
          jira_url="https://miuelpipes1107.atlassian.net/rest/api/3/issue/${{ steps.import-to-xray.outputs.testExecKey }}"
          jira_payload=$(cat <<EOF
          {
            "fields": {
              "summary": "Nuevo nombre del issue"
            }
          }
          EOF
          )
          curl -X PUT \
            "$jira_url" \
            -H "Authorization: Bearer ${{ secrets.XRAY_CLIENT_SECRET }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data "$jira_payload"  