name: automation_regression

on:
  workflow_dispatch:
    inputs:
      testExecKey:
        description: 'Test Exec ID from Xray'
        default: ''
        required: true
        type: string
      projectKey:
        description: 'Project ID from Xray'
        default: ''
        required: true
        type: string

env:
  ROUTE: src/test/java/suites
  NAME_SPACE: "_"
  
jobs:
  job1:
    name: Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  job2:
    needs: job1
    name: Matrix1
    runs-on: ubuntu-latest
    container:
      image: mavster/ubuntu:20.04-ff51-mvn
      options: --user 0

    strategy:
      matrix:
        Plan: [login, details, pnl]

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v3    
          
      - name: Compile and package our project
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x16 -ac &
          export DISPLAY=:99
          export NSS_USE_SHARED_DB=ENABLED
          export $(dbus-launch)
          export NSS_USE_SHARED_DB=ENABLED
          mvn -Dmaven.test.failure.ignore=true test -Dsurefire.suiteXmlFiles=$ROUTE/${{ matrix.Plan }}.xml | tee test_results.txt

      - name: Listar archivos en el directorio 'aws/'
        run: ls -la xray/
        
      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl jq   
           
      - name: "Import results to Xray"
        id: import-to-xray
        uses: mikepenz/xray-action@v3.0.4
        with:
          username: "687D7A60E34D4FF5AEF1FBF7CBC4B8EA"
          password: "cd8d864267f5bd255dfd535afc5075dccc7a56c9cb86e8bc8563ca34e5480732"
          testFormat: "junit"
          testPaths: "**/target/surefire-reports/*.xml"          
          projectKey: ${{ github.event.inputs.projectKey }}
          
      - name: "Use testExecKey"
        run: echo "The testExecKey is ${{ steps.import-to-xray.outputs.testExecKey }}"
        
      - name: Update Test Execution in Xray
        id: update-test-execution
        env:
          XRAY_API_BASE_URL: "https://xray.cloud.getxray.app"
          TEST_EXEC_KEY: ${{ steps.import-to-xray.outputs.testExecKey }}
          XRAY_CLIENT_ID: "687D7A60E34D4FF5AEF1FBF7CBC4B8EA"
          XRAY_CLIENT_SECRET: "cd8d864267f5bd255dfd535afc5075dccc7a56c9cb86e8bc8563ca34e5480732"
        run: |
          # Autenticación con la API de Xray
          echo "Autenticando con la API de Xray..."
          AUTH_RESPONSE=$(curl -s -X POST "$XRAY_API_BASE_URL/api/v2/login" \
            -H "Content-Type: application/json" \
            -d '{"client_id": "'"$XRAY_CLIENT_ID"'", "client_secret": "'"$XRAY_CLIENT_SECRET"'"}')

          # Imprimir la respuesta de autenticación
          echo "Respuesta de autenticación: $AUTH_RESPONSE"

          # Extraer el token
          TOKEN=$(echo $AUTH_RESPONSE | jq -r '.token')

          # Verificar si se obtuvo el token correctamente
          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
            echo "Error: No se pudo obtener el token de autenticación"
            exit 1
          fi

          echo "Token de autenticación obtenido: $TOKEN"

          # Actualizar el resumen (nombre) de la ejecución de prueba existente
          echo "Actualizando el nombre de la ejecución de prueba con key $TEST_EXEC_KEY..."
          UPDATE_RESPONSE=$(curl -s -X PUT "$XRAY_API_BASE_URL/api/v2/testexecutions/$TEST_EXEC_KEY" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            -d '{
              "fields": {
                "summary": "Nuevo nombre para la ejecución de prueba"
              }
            }')

          # Imprimir la respuesta de actualización
          echo "Respuesta de actualización: $UPDATE_RESPONSE"

          # Verificar si la actualización fue exitosa
          if echo "$UPDATE_RESPONSE" | grep -q '"errors"'; then
            echo "Error: No se pudo actualizar la ejecución de prueba"
            exit 1
          fi

          echo "Ejecución de prueba actualizada correctamente"
   
